"""Forward declaration generator — parse function signatures and generate headers."""

import json
import re
from pathlib import Path


def generate_headers(src_dir: Path) -> dict:
    """Parse function signatures from .c files and generate header files.

    Returns stats dict.
    """
    funcs_dir = src_dir / "functions"
    if not funcs_dir.exists():
        return {"error": "No functions directory"}

    include_dir = src_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)

    # Parse signatures from function files
    # Ghidra outputs: return_type function_name(params...)
    sig_pattern = re.compile(
        r'^(\w[\w\s\*]*?)\s+(FUN_[0-9a-f]{8}|thunk_FUN_[0-9a-f]{8}|\w+)\s*\(([^)]*)\)\s*$',
        re.MULTILINE
    )

    prototypes: list[dict] = []

    for f in sorted(funcs_dir.glob("*.c")):
        content = f.read_text()
        # Extract address from filename
        addr = f.stem.split("_")[0] if "_" in f.stem else ""

        for m in sig_pattern.finditer(content):
            ret_type = m.group(1).strip()
            func_name = m.group(2).strip()
            params = m.group(3).strip()

            # Skip if it's inside a comment or the file header
            line_start = content.rfind('\n', 0, m.start()) + 1
            line = content[line_start:m.start()]
            if '//' in line or '/*' in line:
                continue

            prototypes.append({
                "address": addr,
                "name": func_name,
                "return_type": ret_type,
                "params": params,
            })
            break  # One signature per file

    # Write functions.h
    lines = [
        "// Auto-generated function prototypes",
        f"// Total: {len(prototypes)} functions",
        "// Generated by rommer preprocess",
        "",
        "#ifndef FUNCTIONS_H",
        "#define FUNCTIONS_H",
        "",
        '#include "ghidra_types.h"',
        "",
    ]

    for p in prototypes:
        comment = f"  // 0x{p['address']}" if p["address"] else ""
        lines.append(f"{p['return_type']} {p['name']}({p['params']});{comment}")

    lines.extend(["", "#endif // FUNCTIONS_H", ""])

    (include_dir / "functions.h").write_text("\n".join(lines))

    return {
        "prototypes_generated": len(prototypes),
        "header_file": str(include_dir / "functions.h"),
    }
