"""Type resolver — fix Ghidra's generic types across all decompiled function files.

Replaces undefined4, undefined2, undefined1, byte, uint, ushort, etc.
with proper GBA types (u32, u16, u8, s32, etc.).

Also creates ghidra_types.h with standard GBA typedefs.
"""

import re
from pathlib import Path


# Replacement map: Ghidra type → GBA type
TYPE_MAP = {
    r'\bundefined4\b': 'u32',
    r'\bundefined2\b': 'u16',
    r'\bundefined1\b': 'u8',
    r'\bundefined\b': 'u8',
    r'\bbyte\b': 'u8',
    r'\bushort\b': 'u16',
    r'\buint\b': 'u32',
    r'\bulong\b': 'u32',
    r'\blonglong\b': 's64',
}

GHIDRA_TYPES_H = """\
// GBA standard type definitions
// Auto-generated by rommer preprocess

#ifndef GHIDRA_TYPES_H
#define GHIDRA_TYPES_H

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;
typedef signed char s8;
typedef signed short s16;
typedef signed int s32;
typedef signed long long s64;
typedef volatile u8 vu8;
typedef volatile u16 vu16;
typedef volatile u32 vu32;

typedef u32 bool32;
#define TRUE 1
#define FALSE 0
#define NULL ((void*)0)

// GBA memory-mapped IO
#define REG_BASE 0x04000000
#define REG_DISPCNT (*(vu16*)(REG_BASE + 0x000))
#define REG_DISPSTAT (*(vu16*)(REG_BASE + 0x004))
#define REG_VCOUNT (*(vu16*)(REG_BASE + 0x006))
#define REG_KEYINPUT (*(vu16*)(REG_BASE + 0x130))
#define REG_IE (*(vu16*)(REG_BASE + 0x200))
#define REG_IF (*(vu16*)(REG_BASE + 0x202))
#define REG_IME (*(vu16*)(REG_BASE + 0x208))

#endif // GHIDRA_TYPES_H
"""


def resolve_types(src_dir: Path) -> dict:
    """Fix Ghidra types across all function files.

    Returns stats dict.
    """
    funcs_dir = src_dir / "functions"
    if not funcs_dir.exists():
        return {"error": "No functions directory"}

    # Create ghidra_types.h
    include_dir = src_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    (include_dir / "ghidra_types.h").write_text(GHIDRA_TYPES_H)

    files_modified = 0
    total_replacements = 0
    replacement_counts: dict[str, int] = {}

    for f in funcs_dir.glob("*.c"):
        content = f.read_text()
        original = content
        file_replacements = 0

        for pattern, replacement in TYPE_MAP.items():
            count = len(re.findall(pattern, content))
            if count > 0:
                content = re.sub(pattern, replacement, content)
                file_replacements += count
                replacement_counts[replacement] = replacement_counts.get(replacement, 0) + count

        if content != original:
            f.write_text(content)
            files_modified += 1
            total_replacements += file_replacements

    return {
        "files_modified": files_modified,
        "total_replacements": total_replacements,
        "replacements": replacement_counts,
    }
